#CI/CD
name: "Deploy to AWS EC2"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: SSH into EC2 and deploy
        run: |
          # Define EC2 instance details
          echo "${{ secrets.EC2_SSH_KEY }}" > keyPair.pem

          EC2_INSTANCE_IP="54.85.241.65"
          EC2_USER="ubuntu"
          PEM_KEY_PATH="keyPair.pem"

          # Ensure the key file has the correct permissions
          chmod 600 $PEM_KEY_PATH

          # SSH into the EC2 instance and run commands
          ssh -o StrictHostKeyChecking=no -i $PEM_KEY_PATH $EC2_USER@$EC2_INSTANCE_IP << 'EOF'
            set -e  # Exit if any command fails

            export RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}

            # Navigate to the app directory
            cd /home/ubuntu/CA1_Cloud_Application_Development || exit

            # Pull the latest changes from the main branch
            git pull origin main || exit

            # Install dependencies and bundle
            bundle install || exit

            # Run database migrations
            RAILS_ENV=production bundle exec rake db:migrate || exit

            # Run Server
            RAILS_ENV=production bundle exec rails server --binding 0.0.0.0 --port 3000 || exit

            # Restart the app (for example, Puma server)
            sudo systemctl restart puma || exit
          EOF
